import { Link } from "react-router-dom";
import demoNotes from "../../public/demo/notes.md?raw";
import Markdown from "./Markdown";
import Sheet from "./Sheet";
import { DEMO_RUN_ID } from "../api/demo";
import { eyebrow, radius, space } from "../theme";

const TABS = ["Notes", "Flashcards", "Video", "PDF"];

/** The landing hero: the actual product, not a picture of it.
 *
 *  This renders the real notes.md the pipeline produced for the bundled demo
 *  session, through the same Markdown and Sheet components the session viewer
 *  uses. That is deliberate. A screenshot would have to be recaptured every
 *  time the UI moves, and would quietly start lying the first time somebody
 *  forgot. This cannot drift, because it is the thing itself.
 *
 *  It is decoration here, so it is removed from the accessibility tree and
 *  cannot be interacted with: the tab strip is a still of the real one, and
 *  the sheet is clipped with a fade rather than scrolled. The real thing is
 *  one click away and the whole frame is that link.
 */
export default function HeroPreview() {
  return (
    <Link
      to={`/session/${DEMO_RUN_ID}`}
      style={link}
      aria-label="Open the finished session this was generated from"
    >
      <div style={chrome} aria-hidden="true">
        <div style={tabStrip}>
          {TABS.map((t, i) => (
            <span key={t} style={i === 0 ? tabOn : tabOff}>
              {t}
            </span>
          ))}
        </div>

        {/* `inert` spread rather than passed directly: React 18's DOM typings
            predate it, but the attribute itself works and is what actually
            keeps links inside the rendered notes out of the tab order.
            pointer-events is the belt to that braces. */}
        <div style={clip} {...({ inert: "" } as Record<string, string>)}>
          <Sheet>
            <Markdown source={demoNotes} />
          </Sheet>
          {/* className="sheet" so var(--color-bg) inside the gradient
              resolves to the PAPER, not the dark page. Fading to the dark
              surface ran a grey vignette across the diagram and read as a
              rendering artefact rather than a clip. */}
          <div className="sheet" style={fade} />
        </div>
      </div>

      <span style={caption}>
        A real session, generated by the pipeline. Open it →
      </span>
    </Link>
  );
}

const link: React.CSSProperties = {
  display: "block",
  textDecoration: "none",
  color: "inherit",
};

const chrome: React.CSSProperties = {
  border: "1px solid var(--color-divider)",
  borderRadius: radius.lg,
  background: "var(--color-surface)",
  padding: space.md,
  // The one place the system keeps a real shadow: this genuinely floats.
  boxShadow: "var(--shadow-lg)",
};

const tabStrip: React.CSSProperties = {
  display: "flex",
  gap: space.xs,
  marginBottom: space.md,
};

const tabBase: React.CSSProperties = {
  fontFamily: "var(--font-ui)",
  fontSize: 12,
  padding: "5px 12px",
  borderRadius: radius.md,
};

const tabOn: React.CSSProperties = {
  ...tabBase,
  background: "var(--color-accent)",
  color: "var(--color-on-accent)",
};

const tabOff: React.CSSProperties = {
  ...tabBase,
  color: "var(--color-neutral-600)",
};

/** Clipped rather than scrolled: the hero shows that material arrives, it is
 *  not a place to read it. The fade is what says "there is more". */
const clip: React.CSSProperties = {
  position: "relative",
  maxHeight: 340,
  overflow: "hidden",
  pointerEvents: "none",
};

const fade: React.CSSProperties = {
  position: "absolute",
  insetInline: 0,
  bottom: 0,
  height: 120,
  background: "linear-gradient(to bottom, transparent, var(--color-bg))",
};

const caption: React.CSSProperties = {
  ...eyebrow,
  display: "block",
  marginTop: space.sm,
  color: "var(--color-accent-fg)",
};
